language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - cd place
  - echo ready?

script: "./gradlew clean build"

deploy:
  - provider: s3
    access_key_id: "AKIARH7J7IJU3QSD2FDP"
    secret_access_key: "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"
    bucket: "bgpark-update-test"
    skip_cleanup: true
    region: ap-northeast-2
    local_dir: /build/libs

  - provider: codedeploy
    access_key_id: "AKIARH7J7IJU3QSD2FDP"
    secret_access_key: "AKIARH7J7IJU3QSD2FDP"
    bucket: "bgpark-update-test"
    key: nearlog.zip
    bundle_type: zip
    application: bgpark-deploy-app
    deployment_group: bgpark-deploy-app-group
    region: ap-northeast-2
    wait-until-deployed: true

after_deploy:
  - ehco done!

notifications:
  email:
    recipients:
      - bgpark82@gmail.com