language: java
jdk:
  - openjdk8

branches:
  only:
    - feature/NEAR-10

before_install:
  - cd place

script:
  - ./gradlew clean build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $S3_BUCKET
    on:
      all_branches: true

notifications:
  slack: letshadow:l6tgE4ThwuthIXOkqaggHlMO