language: java
jdk:
  - openjdk8

branches:
  only:
    - feature/NEAR-10

before_install:
  - cd place

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.gradle

script:
  - ./gradlew clean build

before_deploy:
  - zip -r nearlog *
  - mkdir -p deploy
  - mv nearlog.zip deploy/nearlog.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $S3_BUCKET
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $S3_BUCKET
    key: deploy/nearlog.zip
    application: nearlog-deploy
    deployment_group: nearlog-group

notifications:
  slack: letshadow:l6tgE4ThwuthIXOkqaggHlMO