version: "3"
services:

  # place 서비스
  place:
    image: place
    ports:
      - "8081:8081"
    restart: always
    networks:
      - nearlog-network

  # user 서비스
  user:
    image: user
    ports:
      - "8082:8082"
    restart: always
    networks:
      - nearlog-network

networks:
  nearlog-network: