version: "3"
services:

  # user 서비스 db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - nearlog-user-db:/var/lib/mysql
    networks:
      - nearlog-network

  # place 서비스
  place:
    image: place
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - db
    networks:
      - nearlog-network

  # user 서비스
  user:
    image: user
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - db
    networks:
      - nearlog-network

networks:
  nearlog-network:

volumes:
  nearlog-user-db: